module.exports = {
  apps: [
    {
      name: 'sso-bridge-frontend',
      script: 'bun',
      args: 'run dev',
      cwd: '/home/work/sso-bridge-system',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 20101,
      },
      error_file: '/home/work/sso-bridge-system/logs/sso-frontend-error.log',
      out_file: '/home/work/sso-bridge-system/logs/sso-frontend-out.log',
      log_file: '/home/work/sso-bridge-system/logs/sso-frontend-combined.log',
      time: true,
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'sso-bridge-backend',
      script: 'bun',
      args: 'run dev',
      cwd: '/home/work/sso-bridge-system/mini-services/sso-backend',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: 20102,
        DATABASE_URL: 'postgresql://postgres:Dbi%402020@66.96.229.251:20301/session_auth',
        REDIS_URL: 'redis://66.96.229.251:20901/0',
        JWT_SECRET: 'SSOBRIDGEDBISECRET2025',
        JWT_ACCESS_TOKEN_EXPIRY: '3600',
        JWT_REFRESH_TOKEN_EXPIRY: '2592000',
        JWT_ID_TOKEN_EXPIRY: '3600',
        ENCRYPTION_KEY: 'c7F9pL2xQ8mR4aT1ZkW6nV3sH0yD5uJe',
        SSO_CALLBACK_URL: 'http://41.216.186.50:20101/api/v1/auth/callback',
        CORS_ORIGIN: '*',
      },
      error_file: '/home/work/sso-bridge-system/logs/sso-backend-error.log',
      out_file: '/home/work/sso-bridge-system/logs/sso-backend-out.log',
      log_file: '/home/work/sso-bridge-system/logs/sso-backend-combined.log',
      time: true,
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
    },
  ],
}
